2020-08-07 15:05:08,467 > INFO > Starting Aruba Upgrade....
2020-08-07 16:07:33,067 > INFO > Starting Aruba Upgrade....
2020-08-07 16:17:41,482 > ERROR > upload_image_tftp
Traceback (most recent call last):
  File "Aruba_Wireless_Upgrade_V1.2.py", line 664, in upload_image_from_server
    if response.find("SUCCESS") != -1:
TypeError: argument should be integer or bytes-like object, not 'str'
2020-08-07 16:20:54,040 > ERROR > upload_image_tftp
Traceback (most recent call last):
  File "Aruba_Wireless_Upgrade_V1.2.py", line 664, in upload_image_from_server
    if response.find("SUCCESS") != -1:
TypeError: argument should be integer or bytes-like object, not 'str'
2020-08-07 16:32:22,373 > ERROR > Login error:10.17.84.220:4343 
Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context,
  File "d:\scripts\py\lib\site-packages\urllib3\util\ssl_.py", line 390, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "d:\scripts\py\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "d:\scripts\py\lib\ssl.py", line 850, in _create
    self.do_handshake()
  File "d:\scripts\py\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "d:\scripts\py\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "d:\scripts\py\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context,
  File "d:\scripts\py\lib\site-packages\urllib3\util\ssl_.py", line 390, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "d:\scripts\py\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "d:\scripts\py\lib\ssl.py", line 850, in _create
    self.do_handshake()
  File "d:\scripts\py\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Aruba_Wireless_Upgrade_V1.2.py", line 212, in get_session
    res = r_session.post(login_url, data = login_post,verify=False)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "d:\scripts\py\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
