2020-09-13 08:11:15,334 > INFO > JOBNAME:1599964875_300507
2020-09-13 08:11:15,334 > INFO > CONFIG FILE:D:\scripts\GIT\Aruba_Controller_upgrade\conf_files\LAB WIRELESS UPGRADE
2020-09-13 08:11:15,370 > INFO > Starting Job
2020-09-13 08:11:15,386 > INFO > INFO:Running: 1599964875_300507 Type:precheck
2020-09-13 08:11:15,400 > INFO > INFO:Starting Configuration LAB WIRELESS UPGRADE Validation
2020-09-13 08:11:15,442 > INFO > Inserting upgrade list to upgrade.db
2020-09-13 08:11:19,498 > INFO > yes
2020-09-13 08:11:19,499 > INFO > INFO:Starting precheck
2020-09-13 08:11:19,513 > INFO > INFO:Executing Precheck
2020-09-13 08:11:19,541 > INFO > INFO:Precheck started for : (MM) NaaS-MM-1:10.17.84.220:4343
2020-09-13 08:11:36,464 > INFO > INFO:Login Success => 10.17.84.220:4343
2020-09-13 08:11:37,127 > INFO > INFO:Executing NaaS-MM-1 - 10.17.84.220:4343 => show clock
2020-09-13 08:13:08,880 > ERROR > ERROR:Precheck failed for => NaaS-MM-1:10.17.84.220:4343
2020-09-13 08:13:08,897 > DEBUG > ERROR:Precheck failed for => NaaS-MM-1:10.17.84.220:4343
2020-09-13 08:13:08,913 > ERROR > Error host pre_post_check
Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context,
  File "d:\scripts\py\lib\site-packages\urllib3\util\ssl_.py", line 390, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "d:\scripts\py\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "d:\scripts\py\lib\ssl.py", line 850, in _create
    self.do_handshake()
  File "d:\scripts\py\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "d:\scripts\py\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "d:\scripts\py\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context,
  File "d:\scripts\py\lib\site-packages\urllib3\util\ssl_.py", line 390, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "d:\scripts\py\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "d:\scripts\py\lib\ssl.py", line 850, in _create
    self.do_handshake()
  File "d:\scripts\py\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\scripts\GIT\Aruba_Controller_upgrade\Aruba_Wireless_Upgrade_APP.py", line 294, in Pre_Post_check
    res = session.get(req_url,verify=False)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "d:\scripts\py\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
2020-09-13 08:13:08,951 > INFO > INFO:Precheck started for : (MD) NaaS-VMC-1:10.17.84.221:4343
2020-09-13 08:13:15,038 > INFO > INFO:Login Success => 10.17.84.221:4343
2020-09-13 08:13:15,095 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show clock
2020-09-13 08:13:17,702 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show version
2020-09-13 08:13:18,569 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show image version
2020-09-13 08:13:19,351 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show storage
2020-09-13 08:13:21,338 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show cpuload
2020-09-13 08:13:22,987 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show memory
2020-09-13 08:13:24,637 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show boot
2020-09-13 08:13:25,474 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show switches
2020-09-13 08:13:28,313 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show switchinfo
2020-09-13 08:13:29,838 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show boot history
2020-09-13 08:13:31,771 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show user
2020-09-13 08:13:33,266 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show ap database long
2020-09-13 08:13:34,541 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show ap bss-table
2020-09-13 08:13:35,791 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show ap essid
2020-09-13 08:13:36,580 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show ap active counters
2020-09-13 08:13:37,362 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show ap debug counters
2020-09-13 08:13:38,133 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show lc-cluster group-membership
2020-09-13 08:13:38,916 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show switches
2020-09-13 08:13:39,750 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show license
2020-09-13 08:13:41,423 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show running-config
2020-09-13 08:13:46,664 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show boot
2020-09-13 08:13:47,489 > INFO > INFO:Executing NaaS-VMC-1 - 10.17.84.221:4343 => show version
2020-09-13 08:13:48,329 > INFO > INFO:Precheck Completed
2020-09-13 08:13:48,360 > INFO > INFO:==== Completed ====
